spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:mysql://localhost:3306/private?serverTimezone=Asia/Seoul
    username: root
    password: qazwsx1@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    hibernate:
      ddl-auto: update
  redis:
    port: 6379
    host: localhost
    password: 1234
    timeout: 3000
firebase:
  project-id: fir-d61fb
  key-path: fir-d61fb-firebase-adminsdk-58xi7-8db4ff70b2.json


zerobase:
  address: "서울시 강남구"

haden:
  admintoken: "AAABnv/xRVklrnYxKZ0aHgTBcXukeZygoC"
  jwtSecret: "mySecret"

logging:
  level:
    org.hibernate:
      SQL: debug
      type.descriptor.sql: trace

